### ISSUE TITLE
combining docs/index.md and README.md

### ISSUE THREAD

**Issue by esmagden** [Photonic-Architecture-Laboratories/si-photonics-toolkit#34]
We have two separate files that are supposed to have exactly the same content. But we have to keep updating both.

e.g: Currently, `index.md` is up-to-date, but `README.md` is not.

Is there a way to make `docs/index.md` point to `README.md` somehow, so that we only update one of them?

**Comment by aycandv** [comment]
It seems there is no direct way of making `docs/index.md` point to `README.md`. One possible solution I think is to create a copy of `README.md` as `docs/README.md` and always keep them in sync.

**Comment by esmagden** [comment]
potential fix with a post-commit-hook:
https://stackoverflow.com/questions/19198787/how-to-conveniently-sync-a-file-between-two-git-repositories
